print("welcome to holiday planner")
print()
print("step 1: pick your holiday type")
print("1- beach holiday")
print("2- chill holiday")
print()
choice = int(input("enter 1 or 2:"))
print()
if choice == 1:
    print("step 2: pick your beach activity")
    print("1- swimming")
    print("2- fishing")
    print()
    beach_activity = int(input("enter 1 or 2:"))
    print()
    if beach_activity == 1:
        print("you picked: swimming")
        print("best time: afternoon")
        print("watch out for sharks")
    else:
        print("you picked: fishing")
        print("best time: evening")
        print("dont get your bait stolen")
elif choice==2:
    print("step 2:")
    print("1-stay at a hotel")
    print("2-go to uluru")
    print()
    chill_activity = int(input("enter 1 or 2:"))
    print()
    if chill_activity== 1:
        print("you picked: stay at a hotel")
        print("best for: sleeping")
        print("make sure to turn off tv")
    else:
        print("you picked: uluru")
        print("best for: taking photos")
        print("dont touch")
else:
    print("that was not a valid choice.")
    print("please enter 1 for beach holiday or 2 for chill holiday")
print()
print("your holiday plan is ready")
print("have fun!")
